### ISSUE TITLE
[UI Issue] : Campaigns are not center aligned on Desktop View

### ISSUE THREAD

**Issue by TartejBrothers** [Briankim254/Unity-Giving#1]
# Issues
- The campaigns page is well designed and looks good on mobile too, but 
![image](https://github.com/Briankim254/Unity-Giving/assets/112921727/5233be05-88cd-4d72-8ddb-c646b4373e5a)
Here this is a problem.
- The search button shows ` cmd + K ` as an option but doesn't work yet.

**Comment by Briankim254** [comment]
- Yes the shortcut and the search command is not functional yet but, be rest assured i am working on it.
- Lastly the campaigns are not design to be centered  but rather be displayed in a grid from the top right.
